### ISSUE TITLE
Tested Full OCR & TICCL & Frog pipeline in web version

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/PICCL#14] opened 2018-02-05 14:35 UTC
I ran project 'DPO35maybe'. This is using the Dutch Martinet book.
- There was no option whatsoever to select an available lexicon. Lexicons for the various languages are available in the data/int/ iternal dirs.
- In the output I see no evidence whatsoever that TICCL actually ran. Apart that is from there being two versions of the paragraphs. This may be a consequence of no lexicon having been available to the system.
- Frog seems to have run the dependency parser. That is very slow and certainly not required by default.

**Comment by martinreynaert** [comment] 2018-02-05 14:44
Correction: I did not test the full pipeline. I selected a version of the book that was already in folia.xml.

**Comment by martinreynaert** [comment] 2018-02-05 14:45
(Sorry, clicked wrong button just there)

**Comment by proycon** [comment] 2018-02-06 12:51
* dependency parser has been disabled by default too (not deployed yet)

**Comment by proycon** [comment] 2018-02-06 12:52
> In the output I see no evidence whatsoever that TICCL actually ran. Apart that is from there being two versions of the paragraphs. This may be a consequence of no lexicon having been available to the system.

It automatically selects the lexicon based on language, I added an override option as requested now. There should be evidence of ticcl running in ``error.log``

**Comment by proycon** [comment] 2018-02-06 12:55
Deployed on mlp01, please test again...

**Comment by martinreynaert** [comment] 2018-02-13 16:54
I tried to upload an English book in a single PDF.

Upload failed. Twice. First time the Hathi-trust book had spaces in the filename. Upload failed. Second time, with file renamed, upload failed again.

For both failures, the user was left clueless.

One of the conclusions for me is that I cannot properly test, let alone further develop, PICCL under the restrictions I am faced with on Ponlyland. We shall need to find a modus vivendi here.

So far, the new PICCL workflow is not demonstrable to anyone, anywhere. Unfortunately.

**Comment by proycon** [comment] 2018-02-13 18:50
Can I find that file somewhere on ponyland? Then I can see if I can reproduce it.

I see a project Morse1 (as you mention on IRC) with a ``JedidiahMorseTheAmericanGazetteer1797.pdf``, 1441792 bytes, md5sum 1e4a8f2e4eb7ba8427ceef1650dc597d .

**Comment by martinreynaert** [comment] 2018-02-13 19:19
The file JedidiahMorseTheAmericanGazetteer1797.pdf is presently uploading to /vol/tensusers/mreynaert .
Unfortunately, this will take quite a while, yet:
martins-mbp:NAMES mre$ scp /Users/mre/OpenGAZAM/Bronteksten/JedidiahMorseTheAmericanGazetteer1797.pdf mreynaert@applejack.science.ru.nl:/vol/tensusers/mreynaert
mreynaert@applejack.science.ru.nl's password: 
JedidiahMorseTheAmericanGazetteer1797.pdf                                                                                                            6%   19MB 119.4KB/s   37:23 ETA

**Comment by martinreynaert** [comment] 2018-02-13 19:20
The file's actual size is: 
martins-mbp:NAMES mre$ ls -l /Users/mre/OpenGAZAM/Bronteksten
total 5470672
-rwxr-xr-x@  1 mre  staff  294232516 Feb 13 16:07 JedidiahMorseTheAmericanGazetteer1797.pdf

**Comment by proycon** [comment] 2018-02-13 20:22
Unable to reproduce from my side, the upload went fine (tested with Firefox). I do have a significantly faster upstream than what you reported (took under a minute). Problem may likely have been client-side.

**Comment by proycon** [comment] 2018-02-14 19:48
Closing this issue, all original points should be resolved by now.

**Closed as completed by proycon** 2018-02-14 19:48 UTC
Labels: enhancement, ready, test
