### ISSUE TITLE
FileExistsError trying to symlink to lexicon file

### ISSUE THREAD

**Issue by JessedeDoes** [LanguageMachines/PICCL#20] opened 2018-02-15 09:00 UTC
[CLAM Dispatcher] Adding to PYTHONPATH: /vol1/lamachine/lib/python3.4/site-packages/PICCL-0.4.2-py3.4.egg/picclservice
[CLAM Dispatcher] Started CLAM Dispatcher v2.1 with picclservice.picclservice (2018-02-14 17:27:51)
[CLAM Dispatcher] Running /vol1/lamachine/bin/python3 "/vol1/lamachine/lib/python3.4/site-packages/PICCL-0.4.2-py3.4.egg/picclservice/picclservice_wrapper.py" "/vol1/lamachine/piccldata/clamdata/projects/j.de.does@umail.leidenuniv.nl/hallo_daar/clam.xml" "/vol1/lamachine/piccldata/clamdata/projects/j.de.does@umail.leidenuniv.nl/hallo_daar/.status" "/vol1/lamachine/piccldata/clamdata/projects/j.de.does@umail.leidenuniv.nl/hallo_daar/input/" "/vol1/lamachine/piccldata/clamdata/projects/j.de.does@umail.leidenuniv.nl/hallo_daar/output/" "/vol1/lamachine/piccldata"
[CLAM Dispatcher] Running with pid 1135 (2018-02-14 17:27:51)
Traceback (most recent call last):
  File "/vol1/lamachine/lib/python3.4/site-packages/PICCL-0.4.2-py3.4.egg/picclservice/picclservice_wrapper.py", line 92, in <module>
    os.symlink(f, 'lexicon.lst')
FileExistsError: [Errno 17] File exists: '/vol1/lamachine/piccldata/data/int/nld/nld.aspell.dict' -> 'lexicon.lst'
[CLAM Dispatcher] Process ended (2018-02-14 17:27:52, 0.482137s) 
[CLAM Dispatcher] Removing temporary files
[CLAM Dispatcher] Status code out of range (256), setting to 127
[CLAM Dispatcher] Finished (2018-02-14 17:27:52), exit code 127, dispatcher wait time 0.44999999999999996s, duration 0.482955s

**Comment by kosloot** [comment] 2018-02-15 09:24
os.symlink() has no 'leave if already there' option. Should work around.
see: https://stackoverflow.com/questions/8299386/modifying-a-symlink-in-python

**Comment by proycon** [comment] 2018-02-15 09:27
I know, this is a duplicate of #18 and has been solved yesterday. Are you on the latest version?

**Comment by JessedeDoes** [comment] 2018-02-15 09:29
Ok, thanks, we will try the latest. We used one from yesterday morning.

**Closed as completed** 2018-05-29 14:33 UTC
Labels: duplicate
